version: '3'
services:
   webapp:
      image: "heliumdatastage/jupyter-datascience:v0.0.3"
      network_mode: service:nginx
      entrypoint:
        - "start-notebook.sh"
      command:
        - "--NotebookApp.base_url=/lw-workspace/proxy"
        - "--NotebookApp.password=''"
        - "--NotebookApp.token=''"
      environment:
        - NAMESPACE=helium
        - HOSTNAME=helium.planx-pla.net
        - FRAME_ANCESTORS=https://helium.planx-pla.net
        - JUPYTER_ENABLE_LAB=yes
      ports: 
         - "${SERVICE_PORT}:8888"
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1024Mi
          reservations:
            cpus: '1.0'
            memory: 1024Mi
   nginx:
      image: "quay.io/cdis/ws-nginx-proxy:2021.01"
      ports:
        - "${SERVICE_PORT}:7780"
      environment:
        - "APP_PORT=8888"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7780/_proxy_status"]
        interval: 1m30s
        timeout: 10s
        retries: 3
